# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/SettingWindow.ui'
#
# Created: Mon Oct  7 14:59:37 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName(_fromUtf8("SettingWindow"))
        SettingWindow.resize(406, 423)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingWindow.sizePolicy().hasHeightForWidth())
        SettingWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/IMG/img/preferences-other.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(SettingWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.intervalDefine = QtGui.QLabel(self.tab)
        self.intervalDefine.setObjectName(_fromUtf8("intervalDefine"))
        self.horizontalLayout_2.addWidget(self.intervalDefine)
        self.intervalSlider = QtGui.QSlider(self.tab)
        self.intervalSlider.setMinimum(5)
        self.intervalSlider.setMaximum(360)
        self.intervalSlider.setSingleStep(30)
        self.intervalSlider.setPageStep(0)
        self.intervalSlider.setProperty("value", 5)
        self.intervalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.intervalSlider.setObjectName(_fromUtf8("intervalSlider"))
        self.horizontalLayout_2.addWidget(self.intervalSlider)
        self.intervalLabel = QtGui.QLabel(self.tab)
        self.intervalLabel.setObjectName(_fromUtf8("intervalLabel"))
        self.horizontalLayout_2.addWidget(self.intervalLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.timeoutDefine = QtGui.QLabel(self.tab)
        self.timeoutDefine.setObjectName(_fromUtf8("timeoutDefine"))
        self.horizontalLayout_4.addWidget(self.timeoutDefine)
        self.timeoutSlider = QtGui.QSlider(self.tab)
        self.timeoutSlider.setMinimum(1)
        self.timeoutSlider.setMaximum(100)
        self.timeoutSlider.setSingleStep(30)
        self.timeoutSlider.setPageStep(0)
        self.timeoutSlider.setProperty("value", 1)
        self.timeoutSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutSlider.setObjectName(_fromUtf8("timeoutSlider"))
        self.horizontalLayout_4.addWidget(self.timeoutSlider)
        self.timeoutLabel = QtGui.QLabel(self.tab)
        self.timeoutLabel.setObjectName(_fromUtf8("timeoutLabel"))
        self.horizontalLayout_4.addWidget(self.timeoutLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mentionsChk = QtGui.QCheckBox(self.tab)
        self.mentionsChk.setObjectName(_fromUtf8("mentionsChk"))
        self.horizontalLayout.addWidget(self.mentionsChk)
        self.commentsChk = QtGui.QCheckBox(self.tab)
        self.commentsChk.setObjectName(_fromUtf8("commentsChk"))
        self.horizontalLayout.addWidget(self.commentsChk)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.usersBlackListWidget = QtGui.QListWidget(self.tab_2)
        self.usersBlackListWidget.setObjectName(_fromUtf8("usersBlackListWidget"))
        self.verticalLayout_3.addWidget(self.usersBlackListWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.btnAddBlackUser = QtGui.QPushButton(self.tab_2)
        self.btnAddBlackUser.setObjectName(_fromUtf8("btnAddBlackUser"))
        self.verticalLayout_4.addWidget(self.btnAddBlackUser)
        self.btnRemoveBlackUser = QtGui.QPushButton(self.tab_2)
        self.btnRemoveBlackUser.setObjectName(_fromUtf8("btnRemoveBlackUser"))
        self.verticalLayout_4.addWidget(self.btnRemoveBlackUser)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_9.addWidget(self.label)
        self.tweetsKeywordsBlacklistWidget = QtGui.QListWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tweetsKeywordsBlacklistWidget.sizePolicy().hasHeightForWidth())
        self.tweetsKeywordsBlacklistWidget.setSizePolicy(sizePolicy)
        self.tweetsKeywordsBlacklistWidget.setObjectName(_fromUtf8("tweetsKeywordsBlacklistWidget"))
        self.verticalLayout_9.addWidget(self.tweetsKeywordsBlacklistWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.btnAddKeyword = QtGui.QPushButton(self.tab_2)
        self.btnAddKeyword.setObjectName(_fromUtf8("btnAddKeyword"))
        self.verticalLayout_10.addWidget(self.btnAddKeyword)
        self.btnRemoveKeyword = QtGui.QPushButton(self.tab_2)
        self.btnRemoveKeyword.setObjectName(_fromUtf8("btnRemoveKeyword"))
        self.verticalLayout_10.addWidget(self.btnRemoveKeyword)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.blockWordwarsCheckBox = QtGui.QCheckBox(self.tab_2)
        self.blockWordwarsCheckBox.setObjectName(_fromUtf8("blockWordwarsCheckBox"))
        self.verticalLayout_6.addWidget(self.blockWordwarsCheckBox)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.maxRetweetsCheckBox = QtGui.QCheckBox(self.tab_2)
        self.maxRetweetsCheckBox.setObjectName(_fromUtf8("maxRetweetsCheckBox"))
        self.horizontalLayout_9.addWidget(self.maxRetweetsCheckBox)
        self.maxRetweetsLimitLineEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxRetweetsLimitLineEdit.sizePolicy().hasHeightForWidth())
        self.maxRetweetsLimitLineEdit.setSizePolicy(sizePolicy)
        self.maxRetweetsLimitLineEdit.setMinimumSize(QtCore.QSize(26, 0))
        self.maxRetweetsLimitLineEdit.setMaximumSize(QtCore.QSize(26, 16777215))
        self.maxRetweetsLimitLineEdit.setObjectName(_fromUtf8("maxRetweetsLimitLineEdit"))
        self.horizontalLayout_9.addWidget(self.maxRetweetsLimitLineEdit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.maxTweetsPerUserCheckBox = QtGui.QCheckBox(self.tab_2)
        self.maxTweetsPerUserCheckBox.setObjectName(_fromUtf8("maxTweetsPerUserCheckBox"))
        self.horizontalLayout_10.addWidget(self.maxTweetsPerUserCheckBox)
        self.maxTweetsPerUserLimitLineEdit = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxTweetsPerUserLimitLineEdit.sizePolicy().hasHeightForWidth())
        self.maxTweetsPerUserLimitLineEdit.setSizePolicy(sizePolicy)
        self.maxTweetsPerUserLimitLineEdit.setMinimumSize(QtCore.QSize(26, 0))
        self.maxTweetsPerUserLimitLineEdit.setMaximumSize(QtCore.QSize(26, 16777215))
        self.maxTweetsPerUserLimitLineEdit.setObjectName(_fromUtf8("maxTweetsPerUserLimitLineEdit"))
        self.horizontalLayout_10.addWidget(self.maxTweetsPerUserLimitLineEdit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.cacheSizeLabel = QtGui.QLabel(self.tab_3)
        self.cacheSizeLabel.setObjectName(_fromUtf8("cacheSizeLabel"))
        self.horizontalLayout_6.addWidget(self.cacheSizeLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cacheViewButton = QtGui.QPushButton(self.tab_3)
        self.cacheViewButton.setObjectName(_fromUtf8("cacheViewButton"))
        self.horizontalLayout_7.addWidget(self.cacheViewButton)
        self.cacheClearButton = QtGui.QPushButton(self.tab_3)
        self.cacheClearButton.setObjectName(_fromUtf8("cacheClearButton"))
        self.horizontalLayout_7.addWidget(self.cacheClearButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingWindow)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.intervalDefine.setBuddy(self.intervalSlider)
        self.timeoutDefine.setBuddy(self.intervalSlider)
        self.label_2.setBuddy(self.mentionsChk)

        self.retranslateUi(SettingWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingWindow.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingWindow.reject)
        QtCore.QObject.connect(self.intervalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), SettingWindow.setIntervalText)
        QtCore.QObject.connect(self.timeoutSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), SettingWindow.setTimeoutText)
        QtCore.QObject.connect(self.btnAddBlackUser, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.addBlackUser)
        QtCore.QObject.connect(self.btnRemoveBlackUser, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.removeBlackUser)
        QtCore.QObject.connect(self.btnAddKeyword, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.addKeyword)
        QtCore.QObject.connect(self.btnRemoveKeyword, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.removeKeyword)
        QtCore.QObject.connect(self.cacheClearButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.clearCache)
        QtCore.QObject.connect(self.cacheViewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingWindow.viewCache)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        SettingWindow.setWindowTitle(QtGui.QApplication.translate("SettingWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalDefine.setText(QtGui.QApplication.translate("SettingWindow", "Interval for notify checking", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalLabel.setText(QtGui.QApplication.translate("SettingWindow", "? ms", None, QtGui.QApplication.UnicodeUTF8))
        self.timeoutDefine.setText(QtGui.QApplication.translate("SettingWindow", "Timeout for popup notify", None, QtGui.QApplication.UnicodeUTF8))
        self.timeoutLabel.setText(QtGui.QApplication.translate("SettingWindow", "? ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingWindow", "Remind me when I have:", None, QtGui.QApplication.UnicodeUTF8))
        self.mentionsChk.setText(QtGui.QApplication.translate("SettingWindow", "@ Me", None, QtGui.QApplication.UnicodeUTF8))
        self.commentsChk.setText(QtGui.QApplication.translate("SettingWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SettingWindow", "<html><head/><body><p align=\"center\">Commentary: </p><p align=\"center\">most debugging problems are fixed easily; <br/>identifying the location of the problem is hard.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("SettingWindow", "Notify", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SettingWindow", "These users won\'t show in any timeline:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddBlackUser.setText(QtGui.QApplication.translate("SettingWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveBlackUser.setText(QtGui.QApplication.translate("SettingWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingWindow", "Tweets with these keywords won\'t show:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddKeyword.setText(QtGui.QApplication.translate("SettingWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveKeyword.setText(QtGui.QApplication.translate("SettingWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.blockWordwarsCheckBox.setText(QtGui.QApplication.translate("SettingWindow", "Block Wordwars (WARNING: High False Positive Rate)", None, QtGui.QApplication.UnicodeUTF8))
        self.maxRetweetsCheckBox.setText(QtGui.QApplication.translate("SettingWindow", "Block Chatting. Retweets Limit Per Tweet:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxTweetsPerUserCheckBox.setText(QtGui.QApplication.translate("SettingWindow", "Block Flooding. Tweets Limit Per User:     ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("SettingWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SettingWindow", "Total Cache Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheSizeLabel.setText(QtGui.QApplication.translate("SettingWindow", "Computing...", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheViewButton.setText(QtGui.QApplication.translate("SettingWindow", "View by File Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheClearButton.setText(QtGui.QApplication.translate("SettingWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("SettingWindow", "Cache", None, QtGui.QApplication.UnicodeUTF8))

import wecase_rc
